### PR TITLE
Adding pre install script for android now cordova build works

### PR DESCRIPTION
**Pull request by wmathurin**
But you need to be running node 0.12 (we are using the child_process new execSync method)

NB: this pull request is for review only - its target is the unstable branch in the wmathurin fork

### CODE REVIEW

**Comment by bhariharan** [comment]
Does ```Cordova 4.0``` offer us anything to solve this problem?

**Comment by wmathurin** [comment]
Not sure.

**Comment by bhariharan** [comment]
:+1:

**Comment by wmathurin** [comment]
Pre install script won't run if you are not running node 0.12.
It will just print warnings. See https://github.com/wmathurin/SalesforceMobileSDK-CordovaPlugin/commit/40d42aca2958805107bc725d3978d851d9bc3d86

I don't think we should fail installing the plugin if you are running an older version of node.
node 0.12 came out in Feb 15

**Comment by bhariharan** [comment]
Maybe we should wait for ```Cordova 4.0``` and revisit. We'll need that for ```Gradle``` anyway.

**Comment by wmathurin** [comment]
Not sure when that will come out and whether it will fix the issue
@akhileshgupta what's your call?

**Comment by khawkins** [comment]
:+1:

**Pull request merged**
